### ISSUE TITLE
What is the `pal_brewer` function?

### ISSUE THREAD

**Issue by EllaKaye** [mccarthy-m-g/palettes#23]
Hi Michael,

I'm working through the code in the Creating a Colour Package vignette and you make use of a `pal_brewer` function. When I run the code, I get an error: `could not find function "pal_brewer"`. I can't find the function anywhere in the `palettes` code base nor in any other R package. What am I missing?

Thanks!

**Comment by mccarthy-m-g** [comment]
Hi Ella,

Thanks for catching this!

I renamed `pal_brewer` to `pal_ramp` during development, but I must have only renamed it in R script files and not the R Markdown files for vignettes. So it’s a typo. Use [`pal_ramp`](https://mccarthy-m-g.github.io/palettes/reference/pal_ramp.html) and you should be good!

None of the code in that vignette gets run so it snuck by the checks. I’ll try to get a patch release out soon to fix this, and will also update the code in the example package.

**Comment by EllaKaye** [comment]
I figured it would be something like that. pal_ramp is a better (more descriptive) name, so good change!
